cloud:
  aws:
    credentials:
      access-key:  dummy
      secret-key: dummy
    region:
      static: eu-central-1
    stack:
      auto: false

application:
  bucket:
    name: my-test-bucket-bkorf
  sourceRoot: classpath
